<?php

namespace Container81AQpgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordValidValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\PasswordValidValidator' shared autowired service.
     *
     * @return \App\Validator\PasswordValidValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/PasswordValidValidator.php';

        return $container->privates['App\\Validator\\PasswordValidValidator'] = new \App\Validator\PasswordValidValidator(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
